trigger:
- master

stages:
  - stage: python
    displayName: Python Setup
    jobs:
      - job: python
        displayName: Download, Setup Environment, Install Dependencies
        pool: 'new agent vm self hosted'
        steps:
          # - task: UsePythonVersion@0
          #   inputs:
          #     versionSpec: '3.7.9'
          #     addToPath: true
          #     architecture: 'x64'

          - task: AzureCLI@2
            inputs:
              azureSubscription: "bot-connection"
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                git clone -b master https://github.com/Thiru799/ansible8.git temp_project
                mkdir -p /d/Projects/demo
                cp -r temp_project/* /d/Projects/demo/
                ls /d/Projects/demo/

          - script: |
              python -m venv venv
              venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
              
              if not exist requirements.txt (
                  echo pytest > requirements.txt
                  echo requests >> requirements.txt
                  echo flask >> requirements.txt
              )

              venv\Scripts\python.exe -m pip install -r requirements.txt
            displayName: 'Create Venv and Install Python Dependencies'

          - script: |
              echo Python dependencies installed successfully!
            displayName: 'Success Message'
            condition: succeeded()
