trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    pytest tests/
  displayName: 'Run tests'

- script: |
    echo "Add other tasks like building docker images or deployment here."
  displayName: 'Other build/deploy tasks'
