trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: |
    python -m venv venv
    call venv\Scripts\activate
    python -m pip install --upgrade pip

    if exist requirements.txt (
        pip install -r requirements.txt
    ) else (
        echo No requirements.txt found, skipping dependency installation.
    )

    pip install pytest
    pytest tests/ || echo Tests failed, but continuing...
  displayName: 'Setup venv, install dependencies, install pytest, and run tests'
